---
- name: Setup macOS environment
  hosts: macos_hosts
  become: yes
  vars:
    brew_packages:
      - git
      - wget
      - htop

  tasks:
    - name: Ensure Homebrew is installed
      stat:
        path: /opt/homebrew/bin/brew
      register: brew_installed

    - name: Install Homebrew if not present (for Apple Silicon)
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: not brew_installed.stat.exists
      become: no

    - name: Install required brew packages
      homebrew:
        name: "{{ item }}"
        state: present
      loop: "{{ brew_packages }}"
